sudo: false 
language: nix 

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

# The different configurations we want to test.
matrix:
  include:
  # Build with different GHC versions and stable package sets
  - env: RESOLVER=lts-11
    compiler: ": #GHC 8.2.2"
  - env: RESOLVER=lts-12
    compiler: ": #GHC 8.4.4"
  - env: RESOLVER=nightly
    compiler: ": #GHC 8.6.1"

  # Build on macOS in addition to Linux
  #  - env: RESOLVER=lts-11
  #    compiler: ": #GHC 8.2.2"
  #    os: osx
  #  - env: RESOLVER=lts-12
  #    compiler: ": #GHC 8.4.4"
  #    os: osx
  #  - env: RESOLVER=nightly
  #    compiler: ": #GHC 8.6.1"
  #    os: osx

script:
- nix-shell -p stack --run \
  "stack test web3:unit --flag web3:solidity --nix --no-terminal --haddock --no-haddock-deps --resolver $RESOLVER"
