sudo: false 
language: cpp

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

# The different configurations we want to test.
matrix:
  # Build with different GHC versions and stable package sets
  include:
  - env: RESOLVER=lts-11
    compiler: ": #GHC 8.2"
  - env: RESOLVER=lts-12
    compiler: ": #GHC 8.4"
  - env: RESOLVER=nightly
    compiler: ": #GHC 8.6"

  - env: RESOLVER=lts-11
    compiler: ": #GHC 8.2"
    os: osx 
  - env: RESOLVER=lts-12
    compiler: ": #GHC 8.4"
    os: osx 
  - env: RESOLVER=nightly
    compiler: ": #GHC 8.6"
    os: osx 

  - env: RESOLVER=lts-11
    compiler: ": #GHC 8.2"
    os: windows 
  - env: RESOLVER=lts-12
    compiler: ": #GHC 8.4"
    os: windows 
  - env: RESOLVER=nightly
    compiler: ": #GHC 8.6"
    os: windows 

install:
- if [[ $TRAVIS_OS_NAME == 'windows' ]]; then choco install haskell-stack; else curl -sSL https://get.haskellstack.org/ | sh; fi

script:
- stack test web3:unit --no-terminal --haddock --no-haddock-deps --resolver $RESOLVER
