sudo: false 
language: nix 

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack. More documentation on each
# of those below.
matrix:
  include:
  # Build with different GHC versions
  - env: RESOLVER=lts-11.22
    compiler: ": #GHC 8.2.2"
  - env: RESOLVER=lts-12.14
    compiler: ": #GHC 8.4.3"
  - env: RESOLVER=nightly
    compiler: ": #GHC 8.6.1"

  # Build on macOS in addition to Linux
  #  - env: RESOLVER=lts-11.22
  #    compiler: ": #GHC 8.2.2"
  #    os: osx
  #  - env: RESOLVER=lts-12.14
  #    compiler: ": #GHC 8.4.3"
  #    os: osx
  #  - env: RESOLVER=nightly
  #    compiler: ": #GHC 8.6.1"
  #    os: osx

script:
- nix-shell -p stack --run \
  "stack test web3:unit --flag web3:solidity --nix --no-terminal --haddock --no-haddock-deps --resolver $RESOLVER"
