name:                web3
version:             0.8.0.0
synopsis:            Ethereum API for Haskell
description:         Web3 is a Haskell client library for Ethereum
github:              "airalab/hs-web3"
license:             BSD3
license-file:        LICENSE
author:              Alexander Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Alexander Krupenkin 2016"
category:            Network

extra-source-files:
- README.md
- CHANGELOG.md
- examples/token/ERC20.hs
- examples/token/ERC20.json
- examples/token/Main.hs
- test/contracts/Registry.json
- test/contracts/SimpleStorage.json
- test/contracts/ComplexStorage.json
- test/contracts/Linearization.json
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/testing.rst
- docs/contributing.rst
- docs/getting_started.rst
- docs/smart_contracts.rst
- docs/ethereum_node_api.rst

dependencies:
- base                 >4.9       && <4.12
- secp256k1-haskell    >=0.1.3    && <0.2
- template-haskell     >=2.11.1.0 && <2.14
- microlens-aeson      >=2.2.0.2  && <2.4
- microlens-mtl        >=0.1.11.0 && <0.2
- microlens-th         >=0.4.1.1  && <0.5
- microlens            >=0.4.8.1  && <0.5
- data-default         >=0.7.1.1  && <0.8
- generics-sop         >=0.3.1.0  && <0.4
- transformers         >=0.5.2.0  && <0.6
- http-client          >=0.5.7.1  && <0.6
- bytestring           >=0.10.8.1 && <0.11
- cryptonite           >=0.23.0.0 && <0.26
- exceptions           >=0.8.3    && <0.11
- basement             >=0.0.4    && <0.1
- machines             >=0.6.3    && <0.7
- OneTuple             >=0.2.1    && <0.3
- relapse              >=1.0.0.0  && <2.0
- tagged               >=0.8.5    && <0.9
- parsec               >=3.1.11.0 && <3.2
- memory               >=0.14.11  && <0.15
- cereal               >=0.5.4.0  && <0.6
- aeson                >=1.1.2.0  && <1.5
- vinyl                >=0.5.3.0  && <0.9
- async                >=2.1.1.1  && <2.3
- text                 >=1.2.2.2  && <1.3
- mtl                  >=2.2.1    && <2.3

ghc-options:
- -funbox-strict-fields
- -Wduplicate-exports
- -Whi-shadowing
- -Widentities
- -Woverlapping-patterns
- -Wpartial-type-signatures
- -Wunrecognised-pragmas
- -Wtyped-holes
- -Wincomplete-patterns
- -Wincomplete-uni-patterns
- -Wmissing-fields
- -Wmissing-methods
- -Wmissing-exported-signatures
- -Wmissing-monadfail-instances
- -Wmissing-signatures
- -Wname-shadowing
- -Wunused-binds
- -Wunused-top-binds
- -Wunused-local-binds
- -Wunused-pattern-binds
- -Wunused-imports
- -Wunused-matches
- -Wunused-foralls
- -Wtabs

flags:
  tls:
    description: Enable TLS support
    default: True 
    manual: True

  debug:
    description: Enable debug compiler options
    default: False
    manual: True

  solidity:
    description: Enable Solidity compiler
    default: False
    manual: True

library:
  source-dirs: src
  when:
  - condition: flag(tls)
    cpp-options:      -DTLS_MANAGER
    dependencies:     http-client-tls

  - condition: flag(debug)
    ghc-options:      -ddump-splices

  - condition: flag(solidity)
    cpp-options:      -DSOLIDITY_COMPILER
    dependencies:     containers
    extra-libraries:  solidity
    c-sources:        ./cbits/solidity_lite.cpp
    include-dirs:     ./cbits

tests:
  unit:
    main:             Spec.hs
    source-dirs:      unit
    dependencies:
    - hspec-expectations   >=0.8.2  && <0.9
    - hspec-discover       >=2.4.8  && <2.6
    - hspec-contrib        >=0.4.0  && <0.6
    - hspec                >=2.4.8  && <2.6
    - web3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  live:
    main:             Spec.hs
    source-dirs:      test
    dependencies:
    - hspec-expectations   >=0.8.2  && <0.9
    - hspec-discover       >=2.4.8  && <2.6
    - hspec-contrib        >=0.4.0  && <0.6
    - hspec                >=2.4.8  && <2.6
    - split                >=0.2.3  && <0.3
    - random               >=1.1    && <1.2
    - time                 >=1.6.0  && <1.9
    - stm                  >=2.4.5  && <2.5
    - web3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
