name:                web3
version:             0.7.3.0
synopsis:            Ethereum API for Haskell
description:         Web3 is a Haskell client library for Ethereum
github:              "airalab/hs-web3"
license:             BSD3
license-file:        LICENSE
author:              Alexander Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Alexander Krupenkin 2016"
category:            Network

extra-source-files:
- README.md
- CHANGELOG.md
- examples/token/ERC20.hs
- examples/token/ERC20.json
- examples/token/Main.hs
- test/contracts/Registry.json
- test/contracts/SimpleStorage.json
- test/contracts/ComplexStorage.json
- test/contracts/Linearization.json

dependencies:
- base                 >4.9       && <4.12
- template-haskell     >=2.12.0.0 && <2.14
- microlens-aeson
- microlens-mtl
- microlens-th
- microlens
- data-default         >=0.7.1.1  && <0.8
- generics-sop         >=0.3.2.0  && <0.4
- transformers         >=0.5.2.0  && <0.6
- http-client          >=0.5.12.1 && <0.6
- bytestring           >=0.10.8.2 && <0.11
- cryptonite           ==0.25.*
- exceptions
- secp256k1
- basement             >=0.0.7    && <0.1
- machines             >=0.6.3    && <0.7
- OneTuple
- relapse
- tagged               >=0.8.5    && <0.9
- parsec               >=3.1.13.0 && <3.2
- memory               >=0.14.16  && <0.15
- cereal               >=0.5.5.0  && <0.6
- aeson                >=1.2.4.0  && <1.5
- vinyl                >=0.8.1.0  && <0.9
- async                >=2.1.1.1  && <2.3
- text                 >=1.2.3.0  && <1.3
- mtl                  >=2.2.2    && <2.3

ghc-options:
- -funbox-strict-fields
- -Wduplicate-exports
- -Whi-shadowing
- -Widentities
- -Woverlapping-patterns
- -Wpartial-type-signatures
- -Wunrecognised-pragmas
- -Wtyped-holes
- -Wincomplete-patterns
- -Wincomplete-uni-patterns
- -Wmissing-fields
- -Wmissing-methods
- -Wmissing-exported-signatures
- -Wmissing-monadfail-instances
- -Wmissing-signatures
- -Wname-shadowing
- -Wunused-binds
- -Wunused-top-binds
- -Wunused-local-binds
- -Wunused-pattern-binds
- -Wunused-imports
- -Wunused-matches
- -Wunused-foralls
- -Wtabs

flags:
  tls:
    description: Enable TLS support
    default: True 
    manual: True

  debug:
    description: Enable debug compiler options
    default: False
    manual: True

  solidity:
    description: Enable Solidity compiler
    default: False
    manual: True

library:
  source-dirs: src
  when:
  - condition: flag(tls)
    cpp-options:      -DTLS_MANAGER
    dependencies:     http-client-tls

  - condition: flag(debug)
    ghc-options:      -ddump-splices

  - condition: flag(solidity)
    cpp-options:      -DSOLIDITY_COMPILER
    dependencies:     containers
    extra-libraries:  solidity
    c-sources:        ./cbits/solidity_lite.cpp
    include-dirs:     ./cbits

tests:
  unit:
    main:             Spec.hs
    source-dirs:      unit
    dependencies:
    - hspec-expectations   >=0.8.2  && <0.9
    - hspec-discover       >=2.4.8  && <2.6
    - hspec-contrib        >=0.4.0  && <0.6
    - hspec                >=2.4.8  && <2.6
    - web3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  live:
    main:             Spec.hs
    source-dirs:      test
    dependencies:
    - hspec-expectations   >=0.8.2  && <0.9
    - hspec-discover       >=2.4.8  && <2.6
    - hspec-contrib        >=0.4.0  && <0.6
    - hspec                >=2.4.8  && <2.6
    - split                >=0.2.3  && <0.3
    - time
    - stm                  >=2.4.5  && <2.5
    - web3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
