# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-16.18

# User packages to be built.
packages:
- 'packages/web3'
- 'packages/ipfs'
- 'packages/scale'
- 'packages/crypto'
- 'packages/jsonrpc'
- 'packages/solidity'
- 'packages/ethereum'
- 'packages/polkadot'
- 'packages/hexstring'
- 'examples/erc20'
- 'examples/scale'
- 'examples/polkadot'

# Extra package dependencies
extra-deps:
- relapse-1.0.0.0@sha256:b89ea23189e07f377be4e2a4deccf3d6ba7f547ed8ad77e27b35d78801efd81c
- vinyl-0.12.1@sha256:03f5e246fae2434250987bbfe708015dc6e23f60c20739c34738acde1383b96c

# Dependencies bounds
pvp-bounds: both

# Nix integration
nix:
    packages:
    - zlib
    - haskellPackages.hlint
    - haskellPackages.stylish-haskell
