# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-12.11

# User packages to be built.
packages:
- '.'

# Dependencies bounds
pvp-bounds: both

# Nix integration
nix:
    packages: [ zlib boost jsoncpp solc solc.dev ]
