# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-12.24

# User packages to be built.
packages:
- '.'

# Extra package dependencies
extra-deps:
- relapse-1.0.0.0

# Dependencies bounds
pvp-bounds: both

# Nix integration
nix:
    packages:
    - zlib
    - boost
    - jsoncpp
    - solc
    - solc.dev
    - haskellPackages.hlint
    - haskellPackages.stylish-haskell
