# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-12.14

# User packages to be built.
packages:
- '.'

# Extra package dependencies
extra-deps:
- secp256k1-haskell-0.1.4
- relapse-1.0.0.0
- vinyl-0.9.3

# Dependencies bounds
pvp-bounds: both

# Nix integration
nix:
    packages:
    - zlib
    - boost
    - jsoncpp
    - solc
    - solc.dev
    - secp256k1
    - haskellPackages.hlint
    - haskellPackages.stylish-haskell
